Repository franksparks/BookJourney, pull requests merged in 2024-08, with the labels that each got.

#39 add scripts for books collection
  scripts/books/delete-book.ts
  scripts/books/get-book-by-id.ts
  scripts/books/get-books-in-list.ts
  scripts/books/insert-book.ts
  scripts/books/update-book.ts
Labels: enhancement

#41 33 booklist actions
  actions/book-list.ts
  db/book-list.ts
  scripts/book-list/delete-book-list.ts
  scripts/book-list/get-book-list-by-list-id.ts
  scripts/book-list/insert-book-list.ts
Labels: enhancement

#40 added actions, db methods and testing scripts for book-status
  actions/book-status.ts
  db/book-status.ts
  prisma/schema.prisma
  scripts/status/delete-book-status.ts
  scripts/status/get-book-status-by-id.ts
  scripts/status/get-book-status-by-user-and-book-id.ts
  scripts/status/get-book-status-by-user-id-and-status.ts
  scripts/status/insert-book-status.ts
  scripts/status/update-book-status.ts
Labels: enhancement

#38 Implemented error handling and testing scripts for the different entities types.
  actions/book-list.ts
  actions/books.ts
  actions/lists.ts
  actions/ratings.ts
  actions/reviews.ts
  components/header.tsx
  db/book-list.ts
  db/book-status.ts
  db/books.ts
  db/lists.ts
  db/ratings.ts
  db/reviews.ts
  db/users.ts
  lib/error-handling.ts
  package.json
  scripts/book-list/delete-book-list.ts
  scripts/book-list/get-book-list-by-list-id.ts
  scripts/book-list/insert-book-list.ts
  scripts/books/delete-book.ts
  scripts/books/get-book-by-id.ts
  scripts/books/get-books-in-list.ts
  scripts/books/insert-book.ts
  scripts/books/update-book-rating-average.ts
  scripts/books/update-book.ts
  scripts/lists/delete-list.ts
  scripts/lists/find-lists-by-user-id.ts
  scripts/lists/insert-list.ts
  scripts/lists/update-list.ts
  scripts/ratings/delete-rating.ts
  scripts/ratings/find-rating-by-book-id-and-user-id.ts
  scripts/ratings/find-ratings-by-book-id.ts
  scripts/ratings/insert-rating-via-action.ts
  scripts/ratings/insert-rating.ts
  scripts/ratings/update-rating.ts
  scripts/reviews/delete-review.ts
  scripts/reviews/find-review-by-book-id-and-user-id.ts
  scripts/reviews/find-reviews-by-book-id.ts
  scripts/reviews/insert-review-via-action.ts
  scripts/reviews/insert-review.ts
  scripts/reviews/update-review.ts
  scripts/status/delete-book-status.ts
  scripts/status/get-book-status-by-id.ts
  scripts/status/get-book-status-by-user-and-book-id.ts
  scripts/status/get-book-status-by-user-id-and-book-id.ts
  scripts/status/get-book-status-by-user-id-and-status.ts
  scripts/status/insert-book-status.ts
  scripts/status/update-book-status.ts
  scripts/users/find-user-by-clerk-id.ts
  scripts/users/find-user-by-user-id.ts
  scripts/users/get-users.ts
  scripts/users/insert-user.ts
Labels: help wanted

#23 Advanced search
  app/layout.tsx
  app/page.tsx
  app/search/page.tsx
  components/AddToList.tsx
  components/PreviewSearchBox.tsx
  components/SearchBar.tsx
  components/SearchBox.tsx
  components/SearchPagination.tsx
  components/SearchRadioButtons.tsx
  components/SearchResults.tsx
  components/header.tsx
  components/ui/dropdown-menu.tsx
  lib/volumes.ts
  package.json
Labels: enhancement, help wanted
